image: ruby:3.0.2

before_script:
  - apt-get update -qq && apt-get install -y nodejs yarn
  - bundle install

stages:
  - test

cache:
  paths:
    - vendor/ruby
    - node_modules

rubocop-lint:
  stage: test
  script:
    - bundle exec rubocop