image: ruby:alpine

before_script:
  - apk add --no-cache --update build-base
  - gem install bundler
  - bundle install

stages:
  - test

cache:
  paths:
    - vendor/ruby

rubocop-lint:
  stage: test
  script:
    - bundle exec rubocop