default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: time_menegment_test
  password: time_menegment_test
  host: localhost

development:
  <<: *default
  database: time_menegment_system

test:
  <<: *default
  database: your_project_name_test

production:
  <<: *default
  database: your_project_name_production
  username: your_project_name
  password: <%= ENV['YOUR_PROJECT_NAME_DATABASE_PASSWORD'] %>